apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}-service
spec:
  selector:
    app: {{ .Values.image.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
