apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: my-namespace

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: small-web-app
      namespace: my-namespace
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: small-web-app
      template:
        metadata:
          labels:
            app: small-web-app
        spec:
          containers:
            - name: small-web-app
              image: small-web-app:1.0
              ports:
                - containerPort: 8000
              env:
                - name: AUTHOR
                  value: "name"
                - name: UUID
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.uid
              readinessProbe:
                httpGet:
                  path: /
                  port: 8000
              livenessProbe:
                httpGet:
                  path: /
                  port: 8000

  - apiVersion: v1
    kind: Service
    metadata:
      name: small-web-app-service
      namespace: my-namespace
    spec:
      selector:
        app: small-web-app
      ports:
        - protocol: TCP
          port: 80
          targetPort: 8000
      type: ClusterIP